### ISSUE TITLE
Remark directive is not handling block contents

### ISSUE THREAD

**Issue by dineshr5** [remarkjs/remark-directive#18]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.1

### Steps to reproduce

The remark-directive does not handling inline block contents. 
<img width="427" alt="Screenshot 2024-08-07 at 7 17 14 PM" src="https://github.com/user-attachments/assets/50aba67d-755e-492b-bb76-eb5f11adab6a">

### Expected behavior

its should return the expected result as like remark-shortcodes.

### Actual behavior

It not handling this scenario which i have mentioned above.

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

**Comment by wooorm** [comment]
I cannot look into your computer or your head. I have no clue what you are asking.

I *think* you’re saying that remark-directive has a different syntax than remark-shortcodes.
That is correct. And intentional. This project is not that project.
See the readme: https://github.com/remarkjs/remark-directive
